[package]
name = "sedsprintf_rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[features]
# Host/dev convenience: enable std by default so `cargo build` / `cargo test` work.
default = ["std"]
std = []

[dependencies]
# put common deps here (none required currently)

# Pull cortex-m ONLY for bare-metal builds (target_os = "none")
[target.'cfg(target_os = "none")'.dependencies]
cortex-m = "0.7"

[profile.release]
opt-level = "z"          # prioritize size ("s" also ok; "z" is smallest)
lto = true               # full LTO (thin LTO also ok; try both)
codegen-units = 1        # better inlining/GC across crates => smaller
panic = "abort"          # you already have this (good)
strip = "symbols"        # since Rust 1.70+: drop debug symbols from artifacts
debug = 0                # ensure no DWARF remains
incremental = false
overflow-checks = false  # off by default in release, make it explicit
